### ISSUE TITLE
XToast构造方法错误

### ISSUE THREAD

**Issue by Reginer** [getActivity/ToastUtils#1]
![image](https://user-images.githubusercontent.com/12568257/45623068-adf40780-bab8-11e8-941a-66d40774addc.png)

![image](https://user-images.githubusercontent.com/12568257/45623115-ccf29980-bab8-11e8-87e7-3286481dd69d.png)

代码是28的

另外 public static void show(Object object) 可否判断下object类型，比如最常用的int的string id都传不了。还得getString

**Comment by getActivity** [comment]
你好，问题已经修复好了，另外现在已经支持传string id，多谢支持
