### ISSUE TITLE
AActivity-->BActivity,点击按钮Button，跳转到CActivity，然后进行操作登录，返回到BActivity，再次点击BActivity中的Button，吐司不显示，因为在WindowHelper中记录的Activity不存在，返回在回到AActivity，同样不显示Toast内容

### ISSUE THREAD

**Issue by lcf687619** [getActivity/ToastUtils#10]
发现你新写的这个有问题，AActivity-->BActivity,点击按钮Button，跳转到CActivity，然后进行操作登录，返回到BActivity，再次点击BActivity中的Button，吐司不显示，因为在WindowHelper中记录的Activity不存在，返回在回到AActivity，同样不显示Toast内容

**Comment by getActivity** [comment]
这个问题我已经在问题#9中答复你了，不要重复提issue
