### ISSUE TITLE
处于后台显示时，样式不对

### ISSUE THREAD

**Issue by songshuilin** [getActivity/ToastUtils#100]
#### 问题描述

* 框架版本【必填】：com.github.getActivity:ToastUtils:11.2

* 问题描述【必填】：处于后台显示，样式不对。
![fde3c36ecf110a0fd36e532fb758ef6](https://user-images.githubusercontent.com/18466715/203517413-f46f73f8-022c-461d-b59d-ea97a180a8db.jpg)

* 复现步骤【必填】：home键切换，支付宝客户端会给失败的回调，然后弹toast（现在app还是处于后台）

* 是否必现【必填】：是

* 出现问题的手机信息【必填】：小米手机 RedmiK30 Pro

* 出现问题的安卓版本【必填】：12

* 问题信息的来源渠道【必填】：本地复现

#### 请回答

* 是部分机型还是所有机型都会出现【必答】：暂时只有小米手机

* 框架最新的版本是否存在这个问题【必答】：是

* 是否已经查阅框架文档还未能解决的【必答】：是

* issue 是否有人曾提过类似的问题【必答】：否

* 是否可以通过 Demo 来复现该问题【必答】：是

* 使用原生的 Toast 是否也会出现该问题【必答】：原生是这样的样式，但是使用哥的框架，切换后台不应该这样显示啊。 处于前台时都正常

**Comment by getActivity** [comment]
小伙子，目前此 issue 打回，原因如下：

* 没有认真看过框架的文档
