### ISSUE TITLE
demo有个问题 

### ISSUE THREAD

**Issue by pengjunhong** [getActivity/ToastUtils#12]
多次点击某个按钮 弹出的toast被保存在一个队列中 然后在点击别的按钮 ，会发现弹出toast的文字内容改变了，但是样式什么的都还是上一个点击的。

**Comment by getActivity** [comment]
这是因为弹吐司的时候会被加入队列，会有所延迟，但是切换样式的时候是立即生效的，实际开发中出发，是不会出现那种特殊需求的

**Comment by pengjunhong** [comment]
好的
