### ISSUE TITLE
按钮快速点击吐司问题

### ISSUE THREAD

**Issue by AnJiuZhe** [getActivity/ToastUtils#14]
例如一个按钮快速点击，每次点击统计次数，并弹出吐司，但是会有延迟显示，可不可以把之前的内容覆盖掉，立即显示最新的吐司内容。

**Comment by AnJiuZhe** [comment]
尝试在吐司前调用ToastUtils.cancel()方法，有些吐司内容会显示不出来，快速点击的话

**Comment by getActivity** [comment]
我已经处理了Toast的显示机制，如果内容相同只显示一次，如果内容不同则依次显示，cancel方法在实际开发中十分少用，基本不会用到，因为Toast会自动消失这一特性，再加上Toast的显示或者取消显示都是通过发送消息，顺序是不会有误的，除非你在显示多个吐司的时候调用cancel方法才会打乱吐司的显示
