### ISSUE TITLE
红米6pro

### ISSUE THREAD

**Issue by 1izheng** [getActivity/ToastUtils#15]
弹窗只出现一次 第二次点击不弹toast。 应该是快速点击的时候 toast不消失 只是文字改变一下这个逻辑吧

**Comment by getActivity** [comment]
吐司显示的规则是这样的，如果同一个时间段内，多次弹出的吐司内容是一致的，则只显示一次，否则会依次进行显示，也就是说会等上一个吐司显示完之后再显示下一个
