### ISSUE TITLE
加载自定义view里面设置的宽度和高度不生效

### ISSUE THREAD

**Issue by yy476853155** [getActivity/ToastUtils#16]
弹出的toast显示的宽高和设置的不一样

**Comment by protectedMan** [comment]
![image](https://user-images.githubusercontent.com/17565737/50138988-49289300-02db-11e9-99da-248e6f2b470f.png)
自定义布局设置match_parent 但是也不生效啊，好像强制适配文字宽度。

![image](https://user-images.githubusercontent.com/17565737/50139139-c18f5400-02db-11e9-91b3-25efb62e57db.png)


我需要这种效果
![image](https://user-images.githubusercontent.com/17565737/50139035-770dd780-02db-11e9-98bd-3d907ce3a92c.png)

**Comment by getActivity** [comment]
长时间没有回复，请到Q群78797078联系我
