### ISSUE TITLE
连续show多个内容可不可以马上更新内容

### ISSUE THREAD

**Issue by Reginer** [getActivity/ToastUtils#21]

**Comment by Reginer** [comment]
用的是项目里提供的apk，连续点击都不显示内容。可以直接显示新的内容么？
![b](https://user-images.githubusercontent.com/12568257/50672876-85ffc400-1015-11e9-8e47-e21f5c7bf479.gif)

**Comment by getActivity** [comment]
ToastUtils的策略就只有排队显示，如果你有那种需求直接fork
