### ISSUE TITLE
切换回上一个页面Toast闪现

### ISSUE THREAD

**Issue by wuzhendev** [getActivity/ToastUtils#23]
你好，使用中发现关闭通知权限后显示Toast，切换回上一个Activity后Toast会闪现一下然后消失，demo也是这样，一加3T 系统版本7.1.1有该问题

**Comment by getActivity** [comment]
关闭通知栏权限之后要重启一下应用才能生效

**Comment by wuzhendev** [comment]
https://github.com/wuzhendev/assets/blob/master/toastutils.mp4

**Comment by wuzhendev** [comment]
https://github.com/wuzhendev/assets/blob/master/toastutils.mp4  我上传了一个截屏，有时间的话麻烦看一下

**Comment by getActivity** [comment]
其他手机有这个问题吗

**Comment by wuzhendev** [comment]
MI6 8.0.0没问题，其他手机手里没有

**Comment by getActivity** [comment]
极少部分手机的问题，我测试其他手机（华为三星）没有这个问题，所以暂时不考虑修复
