### ISSUE TITLE
WindowHelper类中的 ArrayMap 最好用android.support.v4.util.ArrayMap下的，不要用android.util.ArrayMap下的，不然有api 19下的会有问题

### ISSUE THREAD

**Issue by fuyuguang** [getActivity/ToastUtils#28]
小哥 ，你 #WindowHelper类中的 ArrayMap 最好用android.support.v4.util.ArrayMap下的，不要用android.util.ArrayMap下的，不然有api 19下的会有问题！！！

**Comment by BLiYing** [comment]
> 小哥 ，你 #WindowHelper类中的 ArrayMap 最好用android.support.v4.util.ArrayMap下的，不要用android.util.ArrayMap下的，不然有api 19下的会有问题！！！

在api为18的模拟器上试了下，没有什么异常呢。这个具体指什么问题呢？

**Comment by fuyuguang** [comment]
![image](https://user-images.githubusercontent.com/14189642/51359841-65029d00-1b04-11e9-938b-9aea901ecba5.png)

当你指定的minsdkversion 低于api 19时 把 @TargetApi(Build.VERSION_CODES.KITKAT) 去掉后，就
就会告诉你这是一个高版本才有的api，你加@TargetApi(Build.VERSION_CODES.KITKAT) 只是起到了强制压制警告信息作用，在低版本上如果调用这个ArrayMap还是会报错的。

**Comment by getActivity** [comment]
WindowHelper这个类是在没有通知栏权限的情况下才会使用得到，而在判断有没有通知权限的时候，已经将Android 4.4以下的版本设置为有通知栏权限，具体可以看ToastUtils.isNotificationEnabled方法

**Comment by fuyuguang** [comment]
好的，感谢提醒，已确认，确定无此问题。
