### ISSUE TITLE
弹出的速度延迟太长

### ISSUE THREAD

**Issue by lxhtiamo** [getActivity/ToastUtils#3]
吐司弹出来的延迟太久,比系统的慢了0.5秒 ,那没有那种一点就弹出来感觉...

**Comment by getActivity** [comment]
你好，我在代码中设置了0.3秒的延迟，延时的目的在于移除之前的弹吐司任务，避免频繁吐司的弹出造成的不良体验

**Comment by getActivity** [comment]
你好，关于0.3秒延迟的问题已经在最新版本中修复好了，欢迎查阅源码
