### ISSUE TITLE
多语言适配的Bug

### ISSUE THREAD

**Issue by MiracleChen001** [getActivity/ToastUtils#31]
在Dialog中，直接使用ToastUtils.show(R.string.can_not_empty)会出现无法适配多语言的情况，英文环境下仍然弹出的是中文（values资源文件已配好）。通过ToastUtils.show(mActivity.getString(R.string.can_not_empty))这种使用，则可以正常适配多语言。

**Comment by getActivity** [comment]
这个没法整，初始化的时候只传入了Application的对象

**Comment by getActivity** [comment]
你可以在Activity基类再次封装

    /**
     * 显示吐司
     */
    public void toast(CharSequence s) {
        ToastUtils.show(s);
    }

    public void toast(int id) {
        ToastUtils.show(getResources().getString(id));
    }

    public void toast(Object object) {
        ToastUtils.show(object);
    }
