### ISSUE TITLE
oppo a73 bug

### ISSUE THREAD

**Issue by fly2012** [getActivity/ToastUtils#32]
小米6x上正常。
oppo a73上弹不出来，只有app在前台才可以看到，app切到后台了就不行了。
小米6x是android 8.1.0,miui10.2.2.0。
oppo是android 7.1.1,coloros v3.2。

**Comment by getActivity** [comment]
在OPPO手机上通知栏权限有没有被关闭

**Comment by fly2012** [comment]
通知栏权限是打开的。

> 在OPPO手机上通知栏权限有没有被关闭

**Comment by getActivity** [comment]
请通过Q群联系我解决这个问题
