### ISSUE TITLE
crash:has already been added to the window manager

### ISSUE THREAD

**Issue by petma** [getActivity/ToastUtils#33]
java.lang.IllegalStateException: View android.widget.TextView{3728ddd V.ED..... ......ID 0,0-594,133 #102000b android:id/message} has already been added to the window manager.

I use genymotion :google pixel 3,
It happens when I  quick click the view which need toast

**Comment by getActivity** [comment]
这种报错看不出来什么的，请通过Q群联系我解决这个问题

**Comment by getActivity** [comment]
还有模拟器的报错我这边不会修复的，请用真机测试
