### ISSUE TITLE
可否这个地方也设置成可配置的 ，如下

### ISSUE THREAD

**Issue by xyZangGit** [getActivity/ToastUtils#35]
![image](https://user-images.githubusercontent.com/19574114/54095571-f1ce2680-43e2-11e9-9292-0dfb2d74ae21.png)
这个地方是否设置为可配置

**Comment by getActivity** [comment]
给一个修改的理由？

**Comment by xyZangGit** [comment]
这个地方应该是 toast的时间间隔吧，需要同一时间进行不同的吐司，会吐司不出来

**Comment by getActivity** [comment]
你现在是用最新版本的库吗

**Comment by xyZangGit** [comment]
是5.0的版本

**Comment by getActivity** [comment]
更新一下版本库后再试

**Comment by xyZangGit** [comment]
好的，已经更新了，看到新版本的修改了，变成了0.1秒

**Comment by getActivity** [comment]
最新版本上面改成了0.3秒
