### ISSUE TITLE
提 issue 需知

### ISSUE THREAD

**Issue by getActivity** [getActivity/ToastUtils#36]
Github沟通效率实在是很低下，大家伙有问题或者Bug直接到Q群78797078私信给我反馈就OK，我会尽快答复你的问题

**Comment by zkvvv** [comment]
First reply to you

**Comment by cornflower10** [comment]
群搜不到

**Comment by getActivity** [comment]
最近腾讯抽粪了，直接加我的QQ880634解决吧

**Comment by Lieeber** [comment]
如果show Toast之后立马关闭最后一个activity,会报这个错误。WindowManager: android.view.WindowLeaked: Activity ...... has leaked window ...... that was originally added here，最常见的地方就是按两次退出应用的时候，MainActivity销毁了。

**Comment by getActivity** [comment]
你用 ToastUtils 是什么版本的

**Comment by Lieeber** [comment]
8.0

**Comment by dedeTao** [comment]
toast支持自定义动画吗

**Comment by getActivity** [comment]
@dedeTao 可以用悬浮窗框架实现：https://github.com/getActivity/XToast

**Comment by csh159** [comment]
android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
	at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:7931)
	at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:1283)
	at android.view.View.requestLayout(View.java:22139)
	at android.widget.TextView.checkForRelayout(TextView.java:8754)
	at android.widget.TextView.setText(TextView.java:5487)
	at android.widget.TextView.setText(TextView.java:5343)
	at android.widget.TextView.setText(TextView.java:5300)
	at com.hjq.toast.BaseToast.setText(BaseToast.java:32)
	at com.hjq.toast.ToastStrategy.handleMessage(ToastStrategy.java:86)
	at android.os.Handler.dispatchMessage(Handler.java:108)
	at android.os.Looper.loop(Looper.java:166)
	at android.app.ActivityThread.main(ActivityThread.java:7529)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

**Comment by getActivity** [comment]
这个 Toast 的 View 对象是在子线程中创建的？

**Comment by DevYJQ** [comment]
> 如果show Toast之后立马关闭最后一个activity,会报这个错误。WindowManager: android.view.WindowLeaked: Activity ...... has leaked window ...... that was originally added here，最常见的地方就是按两次退出应用的时候，MainActivity销毁了。

这个问题8.2版本也有

**Comment by Archer-cat** [comment]
可以刷新连续快速切换内容吗

**Comment by getActivity** [comment]
不行，Toast 的机制便是如此，以前旧版的 Android 中的 Toast 可以后面覆盖前面的，现在是不行了

**Comment by Archer-cat** [comment]
好的,谢谢回复

**Comment by LiWeiQiangAndroid** [comment]
![image](https://user-images.githubusercontent.com/17853766/118904691-f68cae80-b94c-11eb-87bf-94ceb28e6136.png)
AS 4.2.0
compile_sdk 29
target_sdk 27

**Comment by wadejw** [comment]
> 如果show Toast之后立马关闭最后一个activity,会报这个错误。WindowManager: android.view.WindowLeaked: Activity ...... has leaked window ...... that was originally added here，最常见的地方就是按两次退出应用的时候，MainActivity销毁了。

同遇到..

**Comment by getActivity** [comment]
@wadejw 小伙子，我试了一下没有出现你说的这个问题，你用最新版本会出现这个问题吗？

**Comment by syzhugh** [comment]
这个toast好像不能跨页面展示吧 ？有实现的办法嘛

**Comment by DuranShelf** [comment]
> ![image](https://user-images.githubusercontent.com/17853766/118904691-f68cae80-b94c-11eb-87bf-94ceb28e6136.png) AS 4.2.0 compile_sdk 29 target_sdk 27
> 
> 三星9080 Android 11

这个问题有解决吗, 目前在Android11发现了

**Comment by getActivity** [comment]
@DuranShelf 小伙子，这个内存泄漏是 LeakCanary 自己的，不是你们项目的，所以不需要管。

**Comment by DuranShelf** [comment]
> @DuranShelf 小伙子，这个内存泄漏是 LeakCanary 自己的，不是你们项目的，所以不需要管。

不是的. 如果不集成这个Toast的库, 是不会报这个leaking的, 或者你找个Android11 试一下, 如果在展示Toast的时候, 关闭Activity, 就会报这个leaking, 泄漏的是 topActivity

**Comment by getActivity** [comment]
小伙子，你用的框架是最新版本么？

**Comment by getActivity** [comment]
还有为什么你的栈顶 Activity 是 LeakActivity？这个不是 LeakCanary 里面的类？

**Comment by DuranShelf** [comment]
> 还有为什么你的栈顶 Activity 是 LeakActivity？这个不是 LeakCanary 里面的类？

不是. 我看到有人跟我一样报这个leaking了, 我这边的 图是 topActivity的

**Comment by getActivity** [comment]
小伙子，我刚试过，不会出现，你用的框架是最新版本么？

**Comment by DuranShelf** [comment]
> 小伙子，我刚试过，不会出现，你用的框架是最新版本么？

上边有写哈. 我用的版本是9.5, 那我先去试试 9.6

**Comment by lingdianguole** [comment]
Android 10想在后台弹出toast，怎么弄？

**Comment by getActivity** [comment]
@lingdianguole 如果你想在 Android 10 之后仍然能在后台显示 Toast，请保证应用的通知栏权限或者悬浮窗权限处于开启的状态，除此之外没有任何办法。

**Comment by lingdianguole** [comment]
我找到一种办法，就是在View最上层，用一个TextView展示提示，这样不需要任何权限



At 2022-01-19 17:32:36, "Android轮子哥" ***@***.***> wrote:

@lingdianguole 如果你想在 Android 10 之后仍然能在后台显示 Toast，请保证应用的通知栏权限或者悬浮窗权限处于开启的状态，除此之外没有任何办法。

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by getActivity** [comment]
@lingdianguole 这种能在应用处于后台的情况下显示？

**Comment by getActivity** [comment]
@lingdianguole 小伙子，我想你对后台定义的认知可能不太对的，应用在后台的情况下，是没有任何界面在显示的，就比如你按 Home 键的时候应用已经退到后台了，这个时候你还能看到和应用相关的界面吗？
