### ISSUE TITLE
《急需要改的一点》

### ISSUE THREAD

**Issue by xuxinjiang** [getActivity/ToastUtils#38]
现在Github里面所用的Toast都可以实现连续快速点击都会弹出Toast 为什么这个框架不行 连续点击确没有反应显示 ，测试直接给你bug了，作者是否可以优化一下，不管我点击多少次 速度多快，都可以显示出来 不延时 快速那种 ？QQ478104175

**Comment by getActivity** [comment]
ToastUtils用的是单例吐司，所以是不可能做到跟系统一样的效果

**Comment by getActivity** [comment]
在这块我已经做了优化，依次排队显示Toast

**Comment by getActivity** [comment]
为了避免频繁弹出影响用户体验，相同的内容在极短的时间内只能显示一次
