### ISSUE TITLE
vivox21 在关闭通知权限的情况下，不能显示土司

### ISSUE THREAD

**Issue by weiningpeng** [getActivity/ToastUtils#39]

**Comment by weiningpeng** [comment]
问题已经排除，发现是自己的初始化的时机不对

**Comment by weiningpeng** [comment]
谢谢大佬的热情的技术支持

**Comment by ender115** [comment]
vivo有的手机你打开通知后,会你正在使用APP的时候系统又把通知关了，然后有的时候toast还是弹不出来

**Comment by getActivity** [comment]
禁用通知栏权限后需要重启应用、重启应用、重启应用才能后生效

**Comment by ender115** [comment]
@getActivity 是的呀，我是说vivo有这种你手动打开通知后，玩着玩着APP，系统又给你把通知关了，Toast就弹不出来了，有点恶心，目前就碰到vivo手机有这种情况

**Comment by getActivity** [comment]
问题已经收集，后续我会改善这个问题
