### ISSUE TITLE
请问关于Android7.x系统Toast显示异常BadTokenException最新版本8.0有处理吗？5.2版本依然有这个错误

### ISSUE THREAD

**Issue by BLiYing** [getActivity/ToastUtils#45]
#24302 java.lang.IllegalStateException
View android.widget.TextView{e64f546 V.ED..... ......ID 0,0-0,0 #102000b android:id/message} has already been added to the window manager.
com.hjq.toast.SafeToast$SafeHandler.dispatchMessage(SafeToast.java:64)

出错堆栈：
1 android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:316)
2 android.view.WindowManagerImpl.addView(WindowManagerImpl.java:94)
3 android.widget.Toast$TN.handleShow(Toast.java:469)
4 android.widget.Toast$TN$2.handleMessage(Toast.java:346)
5 android.os.Handler.dispatchMessage(Handler.java:102)
6 com.hjq.toast.SafeToast$SafeHandler.dispatchMessage(SafeToast.java:64)
7 android.os.Looper.loop(Looper.java:163)
8 android.app.ActivityThread.main(ActivityThread.java:6238)
9 java.lang.reflect.Method.invoke(Native Method)
10 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:933)
11 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)

**Comment by getActivity** [comment]
我已经在 8.0 版本修复了此问题，是有一处代码逻辑不严谨导致的，更新到最新版本即可。
