### ISSUE TITLE
关于ToastHelper的cancel方法问题

### ISSUE THREAD

**Issue by zzh12138** [getActivity/ToastUtils#5]
cancel方法里面是根据windowManager是否为空去判断移除的，那如果我在actB里面弹出toast，然后返回到actA，那么windowManager就是null了吧，也就没有移除了。实测vivo X21A有这个问题

**Comment by getActivity** [comment]
你好，感谢反馈，这个问题我已经修复好了，在Activity的onDestroyed方法被调用之前移除WindowManager，下个版本会发布更新，请留意
