### ISSUE TITLE
Android11适配问题

### ISSUE THREAD

**Issue by tengdag** [getActivity/ToastUtils#51]
https://developer.android.com/preview/features/toasts?hl=zh-cn
出于安全方面的考虑，同时也为了保持良好的用户体验，如果包含自定义视图的消息框是以 Android 11 为目标平台的应用从后台发送的，系统会屏蔽这些消息框。请注意，仍允许使用文本消息框；此类消息框是使用 Toast.makeText() 创建的，并不调用 setView()。
由于平台行为发生了变更，以 Android 11 为目标平台的应用会发现文本消息框受到以下负面影响：

getView() 方法返回 null。
以下方法的返回值并不反映实际值，因此您不应在应用中依赖于它们：
getHorizontalMargin()
getVerticalMargin()
getGravity()
getXOffset()
getYOffset()
以下方法是空操作，因此您的应用不应使用它们：
setMargin()
setGravity()

**Comment by getActivity** [comment]
收到，适配中

**Comment by getActivity** [comment]
已经适配，多谢提醒
