### ISSUE TITLE
一次最多显示三个Toast?

### ISSUE THREAD

**Issue by CraftsmanHyj** [getActivity/ToastUtils#52]
在demo类com.hjq.toast.demo.ToastActivity中将弹3次改为10，为什么只会显示最后三个？
```
    public void show1(View v) {
        for (int i = 0; i < 10; i++) {
            ToastUtils.show("我是第" + (i + 1) + "个吐司");
        }
    }
```

只会显示7、8、9这三个

**Comment by getActivity** [comment]
为了用户体验，一次最多连续弹出三个 Toast

**Comment by CraftsmanHyj** [comment]
这个弹出策略是不是可以自定义？

**Comment by getActivity** [comment]
Toast.setToastStrategy() 方法可以自定义策略

**Comment by CraftsmanHyj** [comment]
有没有比较全的API文档。
目前看这个项目好像只能通过demo去慢慢找这些有用的api?
有没有更高效的方式？

**Comment by getActivity** [comment]
没有任何文档，只能看源码，我不推荐你用这个 API

**Comment by CraftsmanHyj** [comment]
额，为什么不推荐使用Toast.setToastStrategy()改变默认策略？

**Comment by getActivity** [comment]
因为这样等于在修改框架的核心源码，可能会引发其他问题，除非你对 ToastUtils 已经非常熟悉了，并且 Toast 也很熟悉，否则你极有可能会写一个 Bug 进去

**Comment by CraftsmanHyj** [comment]
明白了
