### ISSUE TITLE
您好，关于悬浮窗权限影响Toast显示的问题

### ISSUE THREAD

**Issue by ender115** [getActivity/ToastUtils#54]
您好，有的手机没有悬浮窗权限的话Toast也能弹出来，但是偶尔有一些手机不行，请问这个是不是没其他办法解决，只能通过用户手动去打开悬浮窗权限才行

**Comment by getActivity** [comment]
你所用的框架版本号是多少？什么品牌型号的手机会出现这个问题？

**Comment by getActivity** [comment]
长时间没有回复，关闭此 issue
