### ISSUE TITLE
这个是如何解决android11 不能setView的

### ISSUE THREAD

**Issue by liuxgchi** [getActivity/ToastUtils#55]
你好，看您的代没明白是如何解决android11 不能调用setView()方法的，我看自定义的Toast类中，仍然是重载的setView()方法，如果是在android11中，这个可以正常使用吗？谢谢

**Comment by getActivity** [comment]
我这边也在 Android 11 上面做了测试，是可以正常使用的，重载 setView 只是为了获得外层传入的 View 对象，而真正让这个 View 显示到屏幕上面来的不是用 Toast 来显示，而是采用原生的 WindowManager 来实现。

**Comment by liuxgchi** [comment]
明白了，多谢指导！
