### ISSUE TITLE
关于自定义布局

### ISSUE THREAD

**Issue by KotlinLan** [getActivity/ToastUtils#56]
你好，现在遇到一个问题，页面基本上都是采用QQ 风格的toast ，但是只有一两个页面需要自定义布局，
但是发现自定义布局后，全部页面的toast都替换了自定义布局，这种情况怎么处理呢，每次展示QQ风格的toast前调用一下initStyle吗？这样会不会有什么性能损耗，谢谢！

**Comment by getActivity** [comment]
https://github.com/getActivity/XToast

**Comment by getActivity** [comment]
常用的 Toast 布局使用 ToastUtils 框架来显示，而只在一两个地方使用的 Toast 布局请使用 XToast 框架来显示。
