### ISSUE TITLE
把leakcanary升级到2.6后每次弹吐司都会提示内存泄露，您的demo里如果也升到2.6也是一样的

### ISSUE THREAD

**Issue by wangzhongITger** [getActivity/ToastUtils#60]

**Comment by getActivity** [comment]
![](https://user-images.githubusercontent.com/28616817/103971468-9e2af080-51a5-11eb-9793-726d4b1a6231.png)

**Comment by getActivity** [comment]
感谢反馈，我收到这个问题之后第一时间进行了复现，确实有这个问题，但是很遗憾地告诉你，这个内存泄漏不是框架导致的，从泄漏的堆栈来看，没有看到和框架有关的代码。

**Comment by wangzhongITger** [comment]
嗯嗯，是这样的

**Comment by lianyagang** [comment]
override fun onBackPressed() {
//        https://issuetracker.google.com/issues/139738913
        if (Build.VERSION.SDK_INT == Build.VERSION_CODES.Q &&
            isTaskRoot &&
            (supportFragmentManager.primaryNavigationFragment?.childFragmentManager?.backStackEntryCount
                ?: 0) == 0 &&
            supportFragmentManager.backStackEntryCount == 0
        ) {
            finishAfterTransition()
        } else {
            super.onBackPressed()
        }
    }
