### ISSUE TITLE
内存泄漏

### ISSUE THREAD

**Issue by yyzl0418** [getActivity/ToastUtils#61]
┬───
    │ GC Root: Input or output parameters in native code
    │
    ├─ android.os.FileObserver$ObserverThread instance
    │    Leaking: NO (PathClassLoader↓ is not leaking)
    │    Thread name: 'FileObserver'
    │    ↓ Thread.contextClassLoader
    ├─ dalvik.system.PathClassLoader instance
    │    Leaking: NO (ToastUtils↓ is not leaking and A ClassLoader is never leaking)
    │    ↓ ClassLoader.runtimeInternalObjects
    ├─ java.lang.Object[] array
    │    Leaking: NO (ToastUtils↓ is not leaking)
    │    ↓ Object[].[1081]
    ├─ com.hjq.toast.ToastUtils class
    │    Leaking: NO (a class is never leaking)
    │    ↓ static ToastUtils.sToast
    │                        ~~~~~~
    ├─ com.hjq.toast.NormalToast instance
    │    Leaking: YES (This toast is done showing (Toast.mTN.mWM != null && Toast.mTN.mView == null))
    │    Retaining 2.5 kB in 39 objects
    │    mContext instance of com.easypass.carstong.CxtApplicationKt
    │    ↓ NormalToast.mMessageView
    ╰→ android.widget.TextView instance
    ​     Leaking: YES (ObjectWatcher was watching this because android.widget.TextView received
    ​     View#onDetachedFromWindow() callback)
    ​     Retaining 2.5 kB in 38 objects
    ​     key = abb9a153-e665-4431-9a6a-43dbefb0dd99
    ​     watchDurationMillis = 3610
    ​     retainedDurationMillis = -1
    ​     key = 634492b7-0aa9-4a9f-bb51-04658f35cdd5
    ​     watchDurationMillis = 3611
    ​     key = 2c65fe81-c2ac-4977-bd91-8838d942acf2
    ​     key = e3dd9ece-cac7-4bb0-bb17-d623c8eebeea
    ​     key = 0c922753-dbfa-41cf-af2b-1f4b1ffa5e65
    ​     watchDurationMillis = 6974
    ​     retainedDurationMillis = 1973
    ​     key = 66487d7b-dddc-4e0f-9011-40cbd0b8808c
    ​     key = 314ee9b2-f055-49f1-929e-d0530ae3d747
    ​     retainedDurationMillis = 1974
    ​     key = 4b5200c3-4d94-4f4a-8a1e-efb0f93bc3c8
    ​     watchDurationMillis = 12684
    ​     retainedDurationMillis = 7684
    ​     key = 0e257a55-ebd6-42f0-927d-06221ee8feef
    ​     watchDurationMillis = 12685
    ​     retainedDurationMillis = 7685
    ​     key = c943e610-03cb-4b63-b6da-e7474ff3ac4f
    ​     watchDurationMillis = 22463
    ​     retainedDurationMillis = 17463
    ​     View not part of a window view hierarchy
    ​     View.mAttachInfo is null (view detached)
    ​     View.mID = R.id.null
    ​     View.mWindowAttachCount = 4
    ​     mContext instance of com.easypass.carstong.CxtApplicationKt

**Comment by getActivity** [comment]
https://github.com/getActivity/ToastUtils/issues/60
