### ISSUE TITLE
android 7.1.1~android 7.1.2 .Toast$TN$2.handleMessage

### ISSUE THREAD

**Issue by Sirhu173977450** [getActivity/ToastUtils#62]
android 7.1.1~android 7.1.2 .Toast$TN$2.handleMessage 会报这个问题，看是否能判断一个范围值，大于等于7.1.1 小于8,0 都做一下Cach

**Comment by getActivity** [comment]
小伙子，麻烦给一下完整报错信息和堆栈

**Comment by getActivity** [comment]
长时间没有响应，关闭此 issue

**Comment by Sirhu173977450** [comment]
什么意思？写了什么线程
&nbsp;

走自己的路，让别人说去。


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Android轮子哥"<notifications@github.com&gt;; 
发送时间: 2021年1月28日(星期四) 下午3:11
收件人: "getActivity/ToastUtils"<ToastUtils@noreply.github.com&gt;; 
抄送: "老道あ"<173977450@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [getActivity/ToastUtils] android 7.1.1~android 7.1.2 .Toast$TN$2.handleMessage (#62)



Closed #62.

**Comment by TianyaHelp** [comment]
https://bug2048.gitee.io/page/20190428162719.html
