### ISSUE TITLE
内存泄露问题

### ISSUE THREAD

**Issue by libern** [getActivity/ToastUtils#63]
![image](https://user-images.githubusercontent.com/1830640/105727792-632b0a00-5f66-11eb-8a35-22d251a0efe5.png)

当点击按钮，新开一个activity，在activity中使用getActivity/TitleBar，点击返回时，导致内存溢出。

具体步骤：点击按钮新开activity-》点击返回-》显示toast-》在toast还在显示时，再次按钮新开activity-》点击返回-》显示toast（此时这个toast没有显示，而导致的内存泄漏）

![image](https://user-images.githubusercontent.com/1830640/105727953-92da1200-5f66-11eb-9975-1d7e9271e82e.png)

```

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)

        val context = requireContext()
        val activity = requireActivity()

        // 给这个 ToolBar 设置顶部内边距，才能和 TitleBar 进行对齐
        val mTitleBar: TitleBar = view.findViewById(R.id.titleBar)
        mTitleBar.setOnTitleBarListener(object : OnTitleBarListener {
            override fun onLeftClick(v: View) {
                activity.finish()
                ToastUtils.show("左项View被点击")
            }

            override fun onTitleClick(v: View) {
                ToastUtils.show("中间View被点击")
            }

            override fun onRightClick(v: View) {
                ToastUtils.show("右项View被点击")
            }
        })

```

**Comment by getActivity** [comment]
从泄漏的堆栈来看，View 静态持有 Application 对象，但是 Application 作为静态持有是不会导致内存泄漏的，因为静态和 Application 的生命周期是保持一致。

**Comment by getActivity** [comment]
小伙子，你的 LeakCanary 是不是 2.6 版本的？

**Comment by timmy-gzw** [comment]
我也是一样的，报内存泄漏，LeakCanary 是 2.6 版本的

**Comment by getActivity** [comment]
把版本回退到 2.5 就可以了

**Comment by libern** [comment]
这个是LeakCanary的问题么？确定不是你这边需要改些什么吗？

**Comment by getActivity** [comment]
@libern 是的小伙子，我确定以及肯定
