### ISSUE TITLE
leakcanary提示内存泄漏了

### ISSUE THREAD

**Issue by cqsd2021** [getActivity/ToastUtils#65]
NormalToast中的
     /** 吐司消息 View */
    private TextView mMessageView;

**Comment by getActivity** [comment]
https://github.com/getActivity/ToastUtils/issues/63

**Comment by getActivity** [comment]
小伙子，还有别的问题不，没有的话我就关闭 issue 了

**Comment by cqsd2021** [comment]
木有了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年3月13日(周六) 上午9:19
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [getActivity/ToastUtils] leakcanary提示内存泄漏了 (#65)




 
小伙子，还有别的问题不，没有的话我就关闭 issue 了
