### ISSUE TITLE
内存泄漏

### ISSUE THREAD

**Issue by chinamingsss** [getActivity/ToastUtils#66]
┬───
    │ GC Root: Global variable in native code
    │
    ├─ dalvik.system.PathClassLoader instance
    │    Leaking: NO (ToastUtils↓ is not leaking and A ClassLoader is never leaking)
    │    ↓ ClassLoader.runtimeInternalObjects
    ├─ java.lang.Object[] array
    │    Leaking: NO (ToastUtils↓ is not leaking)
    │    ↓ Object[].[3969]
    ├─ com.hjq.toast.ToastUtils class
    │    Leaking: NO (a class is never leaking)
    │    ↓ static ToastUtils.sToast
    │                        ~~~~~~
    ├─ com.hjq.toast.NormalToast instance
    │    Leaking: YES (This toast is done showing (Toast.mTN.mWM != null && Toast.mTN.mView == null))
    │    Retaining 5.0 kB in 45 objects
    │    mContext instance of com.jingcai.apps.qualitydev.base.App
    │    ↓ NormalToast.mMessageView
    ╰→ android.widget.TextView instance
    ​     Leaking: YES (ObjectWatcher was watching this because android.widget.TextView received
    ​     View#onDetachedFromWindow() callback)

**Comment by houjianbo188** [comment]
I has the same question

**Comment by getActivity** [comment]
@chinamingsss @houjianbo188 小伙子们，内存泄漏的问题正在处理中，这个问题正好赶上框架正在重构，加上 jcenter 停止维护，短时间内无法发布版本，所以只能先忍着。这个只是内存泄漏，虽然不会导致应用崩溃，但是我会尽快修复此问题，多谢小伙子们的关注和支持。

**Comment by getActivity** [comment]
已经修复了，下个版本发布。

**Comment by getActivity** [comment]
[toast-9.0.aar.zip](https://github.com/getActivity/ToastUtils/files/6301060/toast-9.0.aar.zip)

**Comment by chinamingsss** [comment]
水水水水水
