### ISSUE TITLE
LeakCanary报内存泄露，该咋办呀？

### ISSUE THREAD

**Issue by liyqxtu** [getActivity/ToastUtils#68]
====================================
HEAP ANALYSIS RESULT
====================================
1 APPLICATION LEAKS

References underlined with "~~~" are likely causes.
Learn more at https://squ.re/leaks.

1763 bytes retained by leaking objects
Signature: d3a6ff3996ea66f68a7b4f3fe264ad07ba63417
┬───
│ GC Root: System class
│
├─ com.hjq.toast.ToastUtils class
│    Leaking: NO (a class is never leaking)
│    ↓ static ToastUtils.sToast
│                        ~~~~~~
├─ com.hjq.toast.NormalToast instance
│    Leaking: YES (This toast is done showing (Toast.mTN.mWM != null && Toast.mTN.mView == null))
│    Retaining 1.8 kB in 28 objects
│    mContext instance of com.xx.xx.activity.d
│    ↓ NormalToast.mMessageView
╰→ android.widget.TextView instance
     Leaking: YES (ObjectWatcher was watching this because android.widget.TextView received
     View#onDetachedFromWindow() callback)
     Retaining 1.7 kB in 27 objects
     key = 50c561a4-d216-4e47-a684-7a7a1329a333
     watchDurationMillis = 13473
     retainedDurationMillis = 8460
     View not part of a window view hierarchy
     View.mAttachInfo is null (view detached)
     View.mID = R.id.null
     View.mWindowAttachCount = 1
     mContext instance of com.xx.xx.activity.d

**Comment by getActivity** [comment]
[toast-9.0.aar.zip](https://github.com/getActivity/ToastUtils/files/6309014/toast-9.0.aar.zip)

**Comment by getActivity** [comment]
小伙子，你试试看这个包会不会

**Comment by liyqxtu** [comment]
新版本啥时候发布呀？

**Comment by getActivity** [comment]
小伙子，框架最新代码已经发布，你可以更新一下版本。

**Comment by getActivity** [comment]
小伙子，还有其他问题不，没有的话我就关闭 issue 了
