### ISSUE TITLE
连点击导致toast不弹出

### ISSUE THREAD

**Issue by inwindtears** [getActivity/ToastUtils#7]
连续点击同一个item，会导致toast很长时间都不会弹出。

**Comment by getActivity** [comment]
你好，这个问题已经修复好了，短时间可以弹多个Toast，但是内容不能重复，现在正在Debug中，后续会发布新版本代码，请留意更新

**Comment by getActivity** [comment]
你好，这个问题已经在最新版本中修复，欢迎下载Demo测试及查阅源码

**Comment by t1one** [comment]
android 9会存在toast消失的问题
