### ISSUE TITLE
之前用的是8.6版本，现在是9.1版本，排队策略问题

### ISSUE THREAD

**Issue by ChawLoo** [getActivity/ToastUtils#71]
感谢大佬的开源，有个问题咨询一下。
旧版本的时候，开多个线程同时调用show，相同的文本是不会重复显示的，新版本会连续弹出，不知道是属于显示的策略改了还是算Bug，我看到新版本底层是用了Handle消息发送，旧版本是会校验文本重复性，新版本是移除了吗？需要自己添加拦截器还是属于Bug问题，望解答，

**Comment by getActivity** [comment]
https://github.com/getActivity/ToastUtils/releases/tag/9.0

**Comment by getActivity** [comment]
小伙子，建议你这边先看一下更新介绍，然后你再看看有没有其他疑问，有的话欢迎再提出来

**Comment by ChawLoo** [comment]
> 小伙子，建议你这边先看一下更新介绍，然后你再看看有没有其他疑问，有的话欢迎再提出来

抱歉，还真没看，那我写个拦截器吧，研究一哈，感谢

**Comment by getActivity** [comment]
@ChawLoo 小伙子，新版本已经没有用排队的方式来显示 Toast 了，具体原因是我发起了一个投票，最终得到的结果是，相比排队显示 Toast，大家更倾向于 Toast 的即时性。

**Comment by getActivity** [comment]
![](https://user-images.githubusercontent.com/28616817/117942914-2977e680-b33e-11eb-8e76-6df10ede2588.png)

**Comment by getActivity** [comment]
小伙子，如果你更倾向 Toast 排队显示的方式，可以通过 `ToastUtils.setStrategy(IToastStrategy strategy)` 这个 API 来重新实现 Toast 的显示规则。

**Comment by getActivity** [comment]
小伙子，你还有别的问题不，没有的话我就关闭 issue 了。
