### ISSUE TITLE
ToastUtils可以设置提示的时间长短吗？

### ISSUE THREAD

**Issue by qianfeifeio** [getActivity/ToastUtils#72]
默认的ToastUtils.show("XXXX"); 有些提交较长的场合 显示的时间太短，可以设置 吐司  Toast时间长点吗？代码怎么调用？

**Comment by getActivity** [comment]
小伙子，你可以通过设置 `ToastUtils.setStrategy(IToastStrategy strategy)` 更改 Toast 显示时长控制 

![](https://user-images.githubusercontent.com/28616817/119635787-97480600-be46-11eb-8167-402c821a8b77.png)

**Comment by getActivity** [comment]
另外一个，如果你只是想针对某一个场景做这一改变，又或者想要显示时间非常长的 Toast，建议你可以搭配 [XToast](https://github.com/getActivity/XToast) 这个框架一起使用，具体搭配方式 Demo 中有注明，你可以参考参考。

**Comment by getActivity** [comment]
小伙子，你这边看看还有其他问题不？没有的话我就关闭 issue 了。
