### ISSUE TITLE
9.0 版本在bugly 上收集到NullPointerException

### ISSUE THREAD

**Issue by ZackLee** [getActivity/ToastUtils#73]
> 
main

java.lang.NullPointerException

Attempt to invoke virtual method 'void android.app.Activity.unregisterActivityLifecycleCallbacks(android.app.Application$ActivityLifecycleCallbacks)' on a null object reference

解析原始
1
com.hjq.toast.WindowLifecycle.unregister(WindowLifecycle.java:92)
2
com.hjq.toast.ToastImpl$2.run(ToastImpl.java:152)
3
android.os.Handler.handleCallback(Handler.java:938)
4
android.os.Handler.dispatchMessage(Handler.java:99)
5
android.os.Looper.loop(Looper.java:233)
6
android.app.ActivityThread.main(ActivityThread.java:7892)
7
java.lang.reflect.Method.invoke(Native Method)
8
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
9
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

**Comment by ZackLee** [comment]
抱歉没有看发版记录，看到已在9.1 版本修复： https://github.com/getActivity/ToastUtils/commit/a045ef2cba4a54c6a4edc88f1b1c8571578deeb9

**Comment by getActivity** [comment]
![](https://user-images.githubusercontent.com/28616817/120160419-cf758d00-c228-11eb-9fb2-a4f9a2b9a2a8.png)
