### ISSUE TITLE
支付宝的样式在9.0之后就废除了吗？

### ISSUE THREAD

**Issue by libern** [getActivity/ToastUtils#74]
好遗憾。。。

**Comment by libern** [comment]
我8.0升级上来，本来用的是，比较喜欢的是大哥做的支付宝的样式。。

**Comment by getActivity** [comment]
是的，多谢小伙子的喜欢，但是这个样式使用的人群比较少，经过深思熟虑，决定只保留最常见的两个，你如果还想要这个样式的话，可以通过实现框架中的样式接口来做。

**Comment by getActivity** [comment]
小伙子，你这边还有其他问题不？没有的话我就关闭 issue 了。

**Comment by libern** [comment]
使用比较少？那感觉你的统计不全面，唉，那示例也没有提供实现方式了吗？

**Comment by getActivity** [comment]
@libern 你可以通过参考旧代码来定义一个样式，然后初始化的时候传入这个样式即可。

**Comment by getActivity** [comment]
@libern 小伙子，这个样式使用次数确实比较少，我删了这个样式那么久，你还是第一个反馈这个问题的人。

**Comment by libern** [comment]
不是我现在反馈，是因为一直用旧版本，现在突然升级下，才遇到这个问题

**Comment by getActivity** [comment]
小伙子，我的意思就是这样，粗略估算一下，我删除这个样式两个月了，这期间应该也有不少人升级，但是唯独只有你反馈了这个问题，说明用这个样式的人不多。

**Comment by getActivity** [comment]
@libern 还有小伙子，你通过框架提供的接口自定义一个这样的样式应该不难吧？我把这个样式删掉了，基本不可能会再加回去了，所以你只能自己加了。

**Comment by libern** [comment]
好的呀，因为最近业务比较忙，还没具体看。等之后我自己升级下，谢谢大哥
