### ISSUE TITLE
小米机型，android 11报错

### ISSUE THREAD

**Issue by JackLiaoJH** [getActivity/ToastUtils#76]
ava.lang.IllegalArgumentException
View=android.widget.TextView{23328a V.ED..... ......ID 0,65-776,197 #7f09075f app:id/tv_content} not attached to window manager

`android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:572)
2
android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:476)
3
android.view.WindowManagerImpl.removeView(WindowManagerImpl.java:139)
4
android.widget.ToastPresenter.show(ToastPresenter.java:207)
5
android.widget.Toast$TN.handleShow(Toast.java:810)
6
android.widget.Toast$TN$1.handleMessage(Toast.java:742)
7
android.os.Handler.dispatchMessage(Handler.java:106)
8
android.os.Looper.loop(Looper.java:236)
9
android.app.ActivityThread.main(ActivityThread.java:8061)
10
java.lang.reflect.Method.invoke(Native Method)
11
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
12
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)`

**Comment by getActivity** [comment]
* 小伙子，请回答我几个问题，以协助我排查该问题。

    1. 你使用的框架版本号是什么？

    2. 你是否在项目中调用过 ToastUtils.setStrategy ？

    3. 除了 Android 11，Android 10 会出现这个问题么？

    4. 如何复现这个问题？复现的步骤是什么样的？

**Comment by JackLiaoJH** [comment]
最新版本，没有调用ToastUtils.setStrategy，目前发现的全是小米手机，android11，线上问题，我们这边也复现不了。不知道只跟android11 小米有关？

**Comment by getActivity** [comment]
小伙子，如果你没有复现步骤，我就没办法排查到具体原因，更没办法帮你做修复的。

**Comment by getActivity** [comment]
目前的崩溃情况是什么样？崩溃次数和用户数分别是多少？

**Comment by getActivity** [comment]
* 还有你们是不是把 Toast 的 View 单例化了？我看了一下 ToastPresenter.show 方法源码，里面的源码是这样写的

```java
public void show(View view, IBinder token, IBinder windowToken, int duration, int gravity,
        int xOffset, int yOffset, float horizontalMargin, float verticalMargin,
        @Nullable ITransientNotificationCallback callback) {
    checkState(mView == null, "Only one toast at a time is allowed, call hide() first.");
    mView = view;
    mToken = token;

    adjustLayoutParams(mParams, windowToken, duration, gravity, xOffset, yOffset,
            horizontalMargin, verticalMargin);
    if (mView.getParent() != null) {
        mWindowManager.removeView(mView);
    }
    try {
        mWindowManager.addView(mView, mParams);
    } catch (WindowManager.BadTokenException e) {
        return;
    }
}
```

* 框架 Toast 的布局都是每次 show 都会去创建新的 View 对象，压根不可能会出现 mView.getParent() != null 的情况，你们检查看看是不是在 ToastStyle.createView 方法中将 View 进行复用了？

public class BlackToastStyle implements IToastStyle<TextView> {

    @Override
    public TextView createView(Context context) {
        TextView textView = new TextView(context);
        .....
        return textView;
    }
}
```

**Comment by JackLiaoJH** [comment]
还蛮多，是单列，view是存储在单列中，好的，那我再看看，谢谢！

**Comment by getActivity** [comment]
如果你们那么写，那不是框架的问题了，就是你们自己的问题了

**Comment by getActivity** [comment]
小伙子，你看看这边还有其他问题不，没有的话我就关闭 issue 了。
