### ISSUE TITLE
设置吐司时长

### ISSUE THREAD

**Issue by jinay-liu** [getActivity/ToastUtils#77]
可以设置吐司时长吗，Toast.LENGTH_LONG还是太短了，想设置久一点，有方法可以设置吗

**Comment by getActivity** [comment]
![](https://user-images.githubusercontent.com/28616817/134859970-e0d67fad-18e7-450f-995e-c1c51e564d14.png)

**Comment by getActivity** [comment]
![](https://user-images.githubusercontent.com/28616817/134860050-e6457cbf-ccb8-4290-b16b-62f6c67c5b8f.png)

**Comment by getActivity** [comment]
小伙子，框架的主页有介绍了，你回去仔细瞅瞅。

**Comment by jinay-liu** [comment]
好的，谢谢
