### ISSUE TITLE
9.6版本LeakCanary会爆各种奇怪的内存泄露，回退到9.5版本就正常了

### ISSUE THREAD

**Issue by android-1995** [getActivity/ToastUtils#79]
如题

**Comment by getActivity** [comment]
小伙子，麻烦提供一下 LeakCanary 上报的内存泄漏堆栈截图

**Comment by android-1995** [comment]
![image](https://user-images.githubusercontent.com/35674533/140453884-d4ff2539-d525-40d6-a713-d612c313aa29.png)
这是奇怪的

**Comment by android-1995** [comment]
![image](https://user-images.githubusercontent.com/35674533/140454097-acf552fe-5941-48ae-b512-766ce68a0d2c.png)
这是有详细信息的

**Comment by android-1995** [comment]
- -上面的打码打了个寂寞 哈哈

**Comment by getActivity** [comment]
小伙子，你使用 Github 上面提供的 Demo 是否能复现该问题？

**Comment by android-1995** [comment]
demo也会的
![image](https://user-images.githubusercontent.com/35674533/140464432-d048af2c-62b8-4454-896c-5f93b5eb1a21.png)

**Comment by android-1995** [comment]
```
   <activity
            android:name=".ToastActivity"
            android:configChanges="orientation|screenSize|keyboardHidden"
            android:launchMode="singleTop"
            android:screenOrientation="portrait">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <action android:name="android.intent.action.VIEW" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>

        <activity
            android:name=".ToastActivity2"
            android:configChanges="orientation|screenSize|keyboardHidden"
            android:screenOrientation="portrait"/>
```

```
startActivity(new Intent(this,ToastActivity2.class));
```
ToastActivity2就是复制的ToastActivity代码

**Comment by getActivity** [comment]
![](https://user-images.githubusercontent.com/28616817/140464744-53ad2241-7d17-4f3e-aab8-793c65651e84.png)

**Comment by getActivity** [comment]
小伙子，0 Distinct Leaks 是没有内存泄漏的意思

**Comment by android-1995** [comment]
是的 我只测试出[跟我项目一样奇怪的那个空信息的泄露](https://github.com/getActivity/ToastUtils/issues/79#issuecomment-961602306)，有信息的没测试出来

**Comment by android-1995** [comment]
一直提示空信息的泄露也很烦 我就回退到9.5了

**Comment by getActivity** [comment]
[ToastUtils-9.8.aar.zip](https://github.com/getActivity/ToastUtils/files/7481278/ToastUtils-9.8.aar.zip)

**Comment by getActivity** [comment]
小伙子，我看了一下，9.6 版本我把弱引用改成软引用，不知道是不是这个问题导致的，我修改了一下代码，你试试看这个包还会不会。

**Comment by android-1995** [comment]
这个包没问题了

**Comment by getActivity** [comment]
OK 的，小伙子，这个包就改了这个地方，你先用着这个 aar 包，如果后续没有其他问题了，我再发布远程依赖上去。
