### ISSUE TITLE
需要变量控制中间或者是底部展示

### ISSUE THREAD

**Issue by liukai2530533** [getActivity/ToastUtils#8]
是不是需要一个变量控制一下呢？我想全局在底部展示，需要在init的时候就传递变量控制

**Comment by liukai2530533** [comment]
在Style中只能getGravity不能设置，我还得自己自定义一个Style,最好是能变量控制

**Comment by getActivity** [comment]
如果你嫌麻烦，可以直接用ToastUtils.getToast().setGravity();这个API
