### ISSUE TITLE
Toast文字显示不全

### ISSUE THREAD

**Issue by protectedMan** [getActivity/ToastUtils#80]
![image](https://user-images.githubusercontent.com/17565737/141262481-cfd14b7f-b8e2-4e08-add9-64159c9765c2.png)
![image](https://user-images.githubusercontent.com/17565737/141262543-c4d8b311-ef75-4117-a475-dc46daf7ecb8.png)
不知道是哪里出了问题, 看了传入到框架内的文字是全的

**Comment by getActivity** [comment]
![](https://user-images.githubusercontent.com/28616817/141264723-38e8848b-d1e3-492d-a892-4899f1d9f83d.png)

**Comment by getActivity** [comment]
小伙子，根据你的描述，我无法复现这个问题，麻烦你提供一下精准的复现步骤。
