### ISSUE TITLE
App有内部语言，然后toast语言不对

### ISSUE THREAD

**Issue by wangsuicheng** [getActivity/ToastUtils#81]
系统语言是中文，App内部切换自身语言成英文，然后show(resId)，这种还是按系统语言toast出来了

**Comment by getActivity** [comment]
![](https://user-images.githubusercontent.com/28616817/141611339-ffda6c44-3f82-46af-bf25-257ba5b1df82.png)

**Comment by getActivity** [comment]
小伙子，ToastUtils 目前使用的 Application 的上下文获取的字符串资源，并不是直接使用系统的上下文获取的，所以不存在读取字符串资源错误的情况，如果有，那么就是你在切换语种的时候，只更新了 Activity 对象里面的语种配置，而没有去更新 Application 对象里面的语种配置。

**Comment by getActivity** [comment]
请自行将问题排查清楚之后，如果确定是 ToastUtils 的问题再反馈给我。
