### ISSUE TITLE
9.6内存泄漏

### ISSUE THREAD

**Issue by hxmeie** [getActivity/ToastUtils#82]
activity中弹出自定义的toast，activity关闭leakcanary总是弹出提示，虽然leakcanary检测为0，但是Android profiler检测出内存中一直存在多个Activity实例，强制垃圾回收也不行。
回退9.5正常，leakcanary也不弹出了

**Comment by hxmeie** [comment]
这个导致activity无法回收

**Comment by getActivity** [comment]
https://github.com/getActivity/ToastUtils/issues/79
