### ISSUE TITLE
Toast可以自定义显示时长

### ISSUE THREAD

**Issue by DodoSpringLove** [getActivity/ToastUtils#84]
Toast可以自定义显示时长

**Comment by DodoSpringLove** [comment]
3s太短了

**Comment by getActivity** [comment]
![](https://user-images.githubusercontent.com/28616817/144042815-eb1997df-2cb5-4e31-b639-04d7cc24f7a6.png)

**Comment by getActivity** [comment]
小伙子，你仔细看过文档了没？

**Comment by DodoSpringLove** [comment]
![image](https://user-images.githubusercontent.com/26377272/144043713-88e9b503-a54a-4499-95af-fd543ac6d740.png)
老大，你这要的不是ToastStregy呀。。。是我的版本不对吗？

**Comment by DodoSpringLove** [comment]
![image](https://user-images.githubusercontent.com/26377272/144043869-55867568-6c1b-4a4c-b947-57400c185258.png)

    implementation 'com.github.getActivity:ToastUtils:9.6'
这是我用的版本，支持Style自定义

**Comment by getActivity** [comment]
升级一下，这个功能是最新版本才有的

**Comment by riggionLin** [comment]
java.lang.NullPointerException: Attempt to invoke interface method 'android.view.View com.hjq.toast.config.IToastStyle.createView(android.content.Context)' on a null object reference
        at com.hjq.toast.ToastStrategy.createToast(ToastStrategy.java:90)
        at com.xiaoe.merchant.ui.knowledge.video.CreateVideoActivity$initClick$3$1.createToast(CreateVideoActivity.kt:103)

**Comment by riggionLin** [comment]
空指针，我是在特定场景下设置的，能否提供长和端时间的显示的方法

**Comment by getActivity** [comment]
@riggionLin 小伙子，我不推荐你修改默认的 Toast 策略，如果因此出现了问题只能靠你自己排查和修复了。
