### ISSUE TITLE
This Toast was not created with Toast.makeText()

### ISSUE THREAD

**Issue by lipiao95** [getActivity/ToastUtils#85]
Bugly收集到了一些错误信息
java.lang.RuntimeException
This Toast was not created with Toast.makeText()
com.hjq.toast.SystemToast.setText(SystemToast.java:1)

Android 11,level 30 OPPO系统

**Comment by getActivity** [comment]
小伙子，麻烦提供一下完整的堆栈信息

**Comment by getActivity** [comment]
还有你使用的框架是什么版本的？

**Comment by lipiao95** [comment]
框架是最新版本  9.6的

堆栈数据：

#2 main

java.lang.RuntimeException

This Toast was not created with Toast.makeText()

解析原始
1
android.widget.Toast.setText(Toast.java:544)
2
com.hjq.toast.SystemToast.setText(SystemToast.java:1)
3
com.hjq.toast.ToastStrategy.handleMessage(ToastStrategy.java:11)
4
android.os.Handler.dispatchMessage(Handler.java:106)
5
android.os.Looper.loop(Looper.java:264)
6
android.app.ActivityThread.main(ActivityThread.java:8282)
7
java.lang.reflect.Method.invoke(Native Method)
8
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
9
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)

就这么点

看了下  出问题的设备全是OPPO PEAM00型号，Android11

**Comment by lipiao95** [comment]
后台弹出toast

**Comment by getActivity** [comment]
小伙子，除了 OPPO 的机子有这个问题，其他机型有这个问题吗？

**Comment by getActivity** [comment]
还有麻烦你提供一下复现步骤给到我这边

**Comment by lipiao95** [comment]
退出应用后台后弹出toast提示，前台没有这个toast处理
目前只观察到oppo这个机型。

**Comment by getActivity** [comment]
![](https://user-images.githubusercontent.com/28616817/144694246-5fa793fb-fe40-47d3-b71f-e79bf1495113.png)

**Comment by getActivity** [comment]
小伙子，我借了一台 OPPO 真机进行了测试，并没有发现你说的这个问题。

**Comment by getActivity** [comment]
小伙子，你如果不能提供准确的复现步骤的话，我是无法给你解决这个问题的，只能等下一个同样遇到这个问题的人来反馈了。

**Comment by getActivity** [comment]
小伙子，你看看这边还有其他问题不，没有的话我就关闭 issue 了。

**Comment by lipiao95** [comment]
我没有复现

**Comment by getActivity** [comment]
那你这么说，我也没有办法了，没有办法复现的问题排查起来犹如大海捞针。

**Comment by getActivity** [comment]
先这样吧，只能等后续的人再反馈吧，我先关闭 issue 了。
