### ISSUE TITLE
显示长时间或者显示短时间的toast要怎么设置，只有一个show方法

### ISSUE THREAD

**Issue by riggionLin** [getActivity/ToastUtils#86]

**Comment by getActivity** [comment]
[https://github.com/getActivity/XToast](https://github.com/getActivity/XToast)

**Comment by getActivity** [comment]
小伙子，你看看这边还有其他问题不，没有的话我就关闭 issue 了。

**Comment by getActivity** [comment]
超过三天没有响应，关闭此 issue。

**Comment by GitHubWebb** [comment]
> 小伙子，框架会自动根据显示的文本长度决定是用长 Toast 或者短 Toast，如果你需要更改某一处地方的 Toast 显示时长，请搭配使用 [XToast](https://github.com/getActivity/XToast) 悬浮窗框架使用。

轮子哥是出于什么考虑决定加入长Toast了
[v11.2](https://github.com/getActivity/Toaster/releases/tag/11.2)
新增框架常见疑问文档

补充和优化框架使用文档
补充显示长短 Toast 方法

**Comment by getActivity** [comment]
@GitHubWebb 框架重构了，顺道一起改了，虽然这个功能不是特别重要，既然有些人有需求，就尽量满足吧。
