### ISSUE TITLE
setView自定义布局大小问题

### ISSUE THREAD

**Issue by wwg90** [getActivity/ToastUtils#87]
如何使用自定义布局的本身宽高，比如使用自定义布局的宽 match_parent

**Comment by wwg90** [comment]
还有一个问题 setView 后 如何取消这个设置？？

**Comment by getActivity** [comment]
![](https://user-images.githubusercontent.com/28616817/146118589-d5b70e1a-65d3-4e89-b0ed-c29692caa4f3.png)

**Comment by getActivity** [comment]
小伙子，你可以使用 XToast 来解决这一问题。

**Comment by wwg90** [comment]
好的  看到了
