### ISSUE TITLE
横屏显示字体过大

### ISSUE THREAD

**Issue by xyhm520** [getActivity/ToastUtils#89]
## 问题描述

* 框架版本：所有

* 问题描述：横屏显示字体过大

* 复现步骤：横屏显示字体过大

* 是否必现：是

* 手机信息：华为p30

**Comment by getActivity** [comment]
Github 上提供的 Demo 是否有这个问题？

**Comment by getActivity** [comment]
小伙子，结果咋样了？还有你如果长时间不回复的话，我会认为你的问题已经解决了，我就会主动关闭这个 issue 了。

**Comment by getActivity** [comment]
超过三天没有响应，关闭此 issue。

**Comment by isgetzz** [comment]
dialog show 以后 toast 布局就异常变得很大，其他手机正常

**Comment by getActivity** [comment]
@isgetzz 小伙子，你的项目是使用 AutoSize 框架对吧？
