### ISSUE TITLE
窗口泄漏

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [getActivity/ToastUtils#90]
## 问题描述

* 框架版本：最新版

* 问题描述：页面发生旋转activity销毁时吐司未消失，窗口泄漏 WindowLeaked

* 复现步骤：使用 ToastUtils.debugShow 在程序暂停恢复时弹吐司，旋转屏幕时必现

* 是否必现：是

* 手机信息：一加五 / Android 10

* 框架最新的版本是否存在这个问题：是

* 使用原生的 Toast 是否也会出现该问题：否

![image](https://user-images.githubusercontent.com/54784104/148187527-b0074827-88cf-4dab-b109-0d30d3b86b1f.png)

**Comment by getActivity** [comment]
[ToastUtils-10.2.aar.zip](https://github.com/getActivity/ToastUtils/files/7814124/ToastUtils-10.2.aar.zip)

**Comment by getActivity** [comment]
经过核实，确实存在这个问题，现在已经修复了，小伙子你可以下载这个修复包试试看

**Comment by SaltedFish-Extreme** [comment]
> 经过核实，确实存在这个问题，现在已经修复了，小伙子你可以下载这个修复包试试看

好的

**Comment by getActivity** [comment]
小伙子，版本更新了，你更新一下远程依赖即可。

**Comment by SaltedFish-Extreme** [comment]
> 小伙子，版本更新了，你更新一下远程依赖即可。

好的👌
