### ISSUE TITLE
轮子哥，使用debugshow时候，显示toast时候关闭程序会报窗口泄漏异常😂上次提窗口泄漏问题还是旋转屏幕时候，问题描述大体类似就不说了，直接上图吧😂

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [getActivity/ToastUtils#92]
![image](https://user-images.githubusercontent.com/54784104/150642743-249b534d-303d-4d7a-92c9-a8327f3bd89d.png)

**Comment by getActivity** [comment]
小伙子，我现在进行了复现，调用 debugShow 之后进行屏幕旋转并没有复现出现你说的窗口泄漏问题。

**Comment by SaltedFish-Extreme** [comment]
> 小伙子，我现在进行了复现，调用 debugShow 之后进行屏幕旋转并没有复现出现你说的窗口泄漏问题。

啊，我知道，旋转屏幕那个已经修复了，上次的issus#90是我提的已经修复了😂，这次的情况是显示toast时候直接关闭程序时候出现的，因为大体情况类似，不想再填一次模板了，所以我才这么说的😂

**Comment by getActivity** [comment]
我这边还是不能复现，在显示 Toast 的时候立马按返回键不会出现 WindowLeaked 的问题。

**Comment by SaltedFish-Extreme** [comment]
> 我这边还是不能复现，在显示 Toast 的时候立马按返回键不会出现 WindowLeaked 的问题。

我这边几乎必现，debugShow刚显示toast立马按返回键关闭程序就这样
![image](https://user-images.githubusercontent.com/54784104/150664255-64161dfa-b031-45b0-9414-a22389ed02d4.png)

**Comment by SaltedFish-Extreme** [comment]
> 我这边还是不能复现，在显示 Toast 的时候立马按返回键不会出现 WindowLeaked 的问题。

就算不立马按也是一样，只要是toast显示中时，按返回键关闭程序，logcat就会出现这个

**Comment by getActivity** [comment]
小伙子，你用 Github 上面提供的 Demo 看看能不能复现这个问题？

**Comment by SaltedFish-Extreme** [comment]
> 小伙子，你用 Github 上面提供的 Demo 看看能不能复现这个问题？

可以，我点击第一个示例，显示吐司时候一直按返回键退出就这样
![image](https://user-images.githubusercontent.com/54784104/150667216-858858b7-6d0d-475b-bbdc-59b7d83c67b4.png)

**Comment by getActivity** [comment]
![](https://user-images.githubusercontent.com/28616817/150668758-a5f791dd-5ca1-4795-beb0-5f9a5a2930f7.png)

**Comment by getActivity** [comment]
![](https://user-images.githubusercontent.com/28616817/150668786-b207a5ef-db10-4c42-a44c-e952c114bf57.png)

**Comment by getActivity** [comment]
![](https://user-images.githubusercontent.com/28616817/150668794-475ed651-62e3-424c-bec2-5490082589c6.png)

**Comment by getActivity** [comment]
小伙子，你 debug 一下这些代码，看看按下返回键之后的调用链是什么样的？并告诉我调用了哪些代码？代码用行号表达。

**Comment by getActivity** [comment]
![](https://user-images.githubusercontent.com/28616817/150785551-80724ba2-7269-4fe4-b8ad-e21ad6bc71a9.png)

**Comment by getActivity** [comment]
小伙子，远程依赖已经更新了，更新一下即可。

**Comment by SaltedFish-Extreme** [comment]
> 小伙子，远程依赖已经更新了，更新一下即可。

好的👌
