### ISSUE TITLE
toast show的内容变成一串数字

### ISSUE THREAD

**Issue by protectedMan** [getActivity/ToastUtils#93]
最近我们线上环境偶现，toast内容为一串数字的情况。
![IMG_1820(20220213-094803)](https://user-images.githubusercontent.com/17565737/153735040-6c561664-6032-419d-93d6-7750591086c0.PNG)
经确认，代码上showtoast的是写死的文字。但是显示出来的是确是一串数字。
这种异常情况在重新安装客户端后消失。

现在完全想不到是什么问题？作者这里能提供一些排查思路吗

**Comment by getActivity** [comment]
小伙子，我认真检查了一下代码，代码写法是没有任何问题。

**Comment by ff-frida** [comment]
> 最近我们线上环境偶现，toast内容为一串数字的情况。 ![IMG_1820(20220213-094803)](https://user-images.githubusercontent.com/17565737/153735040-6c561664-6032-419d-93d6-7750591086c0.PNG) 经确认，代码上showtoast的是写死的文字。但是显示出来的是确是一串数字。 这种异常情况在重新安装客户端后消失。
> 
> 现在完全想不到是什么问题？作者这里能提供一些排查思路吗

看数字让我想到资源唯一id，也就是字符串资源string中写的name，在编译之后R.string.xxxx是一个十六进制的id来的，上面的数字转换16进制后1378e970，可以反编译apk，然后搜索0x1378e970是什么

**Comment by protectedMan** [comment]
> > 最近我们线上环境偶现，toast内容为一串数字的情况。 ![IMG_1820(20220213-094803)](https://user-images.githubusercontent.com/17565737/153735040-6c561664-6032-419d-93d6-7750591086c0.PNG) 经确认，代码上showtoast的是写死的文字。但是显示出来的是确是一串数字。 这种异常情况在重新安装客户端后消失。
> > 现在完全想不到是什么问题？作者这里能提供一些排查思路吗
> 
> 看数字让我想到资源唯一id，也就是字符串资源string中写的name，在编译之后R.string.xxxx是一个十六进制的id来的，上面的数字转换16进制后1378e970，可以反编译apk，然后搜索0x1378e970是什么
感谢提醒,经过排查,并没有发现是资源ID的问题

**Comment by protectedMan** [comment]
> > 最近我们线上环境偶现，toast内容为一串数字的情况。 ![IMG_1820(20220213-094803)](https://user-images.githubusercontent.com/17565737/153735040-6c561664-6032-419d-93d6-7750591086c0.PNG) 经确认，代码上showtoast的是写死的文字。但是显示出来的是确是一串数字。 这种异常情况在重新安装客户端后消失。
> > 现在完全想不到是什么问题？作者这里能提供一些排查思路吗
> 
> 看数字让我想到资源唯一id，也就是字符串资源string中写的name，在编译之后R.string.xxxx是一个十六进制的id来的，上面的数字转换16进制后1378e970，可以反编译apk，然后搜索0x1378e970是什么

感谢提醒,经过排查,并没有发现是资源ID的问题
