### ISSUE TITLE
Fatal Exception: java.lang.RuntimeException: This Toast was not created with Toast.makeText()

### ISSUE THREAD

**Issue by yinyangwu** [getActivity/ToastUtils#94]
## 问题描述

* 框架版本：com.github.getActivity:ToastUtils:10.0

* 问题描述：Firebase Crashlytics线上用户出现崩溃情况

* 复现步骤：未能复现

* 是否必现：否

* 手机信息：Android 11 Redmi Note 10 5G

## 请回答

* 是部分机型还是所有机型都会出现：部分

* 框架最新的版本是否存在这个问题：最新版本是10.3，下个版本用上

* 是否已经查阅框架文档还未能解决的：是

* issue 是否有人曾提过类似的问题：否（

* 是否可以通过 Demo 来复现该问题：否

* 使用原生的 Toast 是否也会出现该问题：否

## 其他

```
Fatal Exception: java.lang.RuntimeException: This Toast was not created with Toast.makeText()
       at android.widget.Toast.setText(Toast.java:546)
       at com.hjq.toast.SystemToast.setText(SystemToast.java:38)
       at com.hjq.toast.ToastStrategy$1.run(ToastStrategy.java:135)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:236)
       at android.app.ActivityThread.main(ActivityThread.java:8051)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)
```
<img width="1085" alt="image" src="https://user-images.githubusercontent.com/7466810/159638010-f91d1077-9abe-4fc9-ac0c-d9eb7f5a876f.png">
<img width="1075" alt="image" src="https://user-images.githubusercontent.com/7466810/159638088-8186c4f0-fba4-4919-b6ee-705b73eb7e02.png">

**Comment by getActivity** [comment]
<img width="459" alt="image" src="https://user-images.githubusercontent.com/28616817/159669933-aa7c5100-8589-4d3a-bfba-e6a6e81ae867.png">

**Comment by yinyangwu** [comment]
> <img alt="image" width="459" src="https://user-images.githubusercontent.com/28616817/159669933-aa7c5100-8589-4d3a-bfba-e6a6e81ae867.png">

是的，我们下个版本还没发版，线上用户还没用上ToastUtils新版本

**Comment by getActivity** [comment]
小伙子，你更新到最新版本再试试看有没有这个问题，如果还是有的话再反馈给我。

**Comment by yinyangwu** [comment]
可以，下周再反馈吧

**Comment by getActivity** [comment]
小伙子，升级到最新版本之后还有出现这个问题吗？

**Comment by yinyangwu** [comment]
暂时没遇到了

**Comment by gfzy9876** [comment]
implementation 'com.github.getActivity:ToastUtils:11.0'
还是出现这个问题了，堆栈如下：
<img width="726" alt="image" src="https://github.com/getActivity/Toaster/assets/34124544/886de2c2-8ce6-4bb9-aa7f-ece0bda38658">
@getActivity

**Comment by getActivity** [comment]
@gfzy9876 小伙子，最新版本已经修复了这个问题，你更新到最新版本再看看。

**Comment by gfzy9876** [comment]
> @gfzy9876 小伙子，最新版本已经修复了这个问题，你更新到最新版本再看看。

大佬方便告知下什么原因和解决方案嘛😜

**Comment by getActivity** [comment]
> > @gfzy9876 小伙子，最新版本已经修复了这个问题，你更新到最新版本再看看。
> 
> 大佬方便告知下什么原因和解决方案嘛😜

https://github.com/getActivity/Toaster/commit/3803295d45e457c6b29ef8c35f5ec24326e80a6f

**Comment by w296365959** [comment]
com.github.getActivity:ToastUtils:11.2   也出现了这个问题

**Comment by getActivity** [comment]
> com.github.getActivity:ToastUtils:11.2 也出现了这个问题

@w296365959 框架最新版本已经处理该问题，更新一下到最新版本即可解决
