### ISSUE TITLE
请教一下

### ISSUE THREAD

**Issue by Horicer** [getActivity/ToastUtils#95]
从A页面跳转到B页面，然后在B页面提示toast完立马关闭B页面，这个时候toast就马上消失了，是这样的吗

**Comment by getActivity** [comment]
小伙子，你自己试一下不就知道了？

**Comment by Horicer** [comment]
试了，回到A页面就看不到toast了

**Comment by getActivity** [comment]
你应该是在 B 页面停留了一会儿才关闭，因为框架做了延迟 200 毫秒后显示，要不然 Toast 是不会停留在 B 页面上显示的。

**Comment by getActivity** [comment]
你现在有两个解决方案，第一个就是把 Toast 显示后立马关闭当前 B Activity，这样 200 毫秒后 Toast 就是在 A Activity 上面，第二种方案是使用 delayedShow 方法来显示 Toast，将 Toast 的延迟显示时间向后延长，这样才能保证 B Activity 已经销毁，A Activity 才是栈顶的  Activity。

**Comment by Horicer** [comment]
会随着当前的activity生命周期而销毁吧

**Comment by getActivity** [comment]
是的
