### ISSUE TITLE
吐司内存泄漏

### ISSUE THREAD

**Issue by zkzk7749** [getActivity/ToastUtils#96]
* 框架版本【必填】：最新版本，10.5

* 问题描述【必填】：
1.内存泄漏，
2.系统提示，E/Toast: setGravity() shouldn't be called on text toasts, the values won't be used

* 复现步骤【必填】：您的demo源码中就可以看见，多点几次吐司就会出来
* 我复制下来，
* com.hjq.toast.demo D/LeakCanary: Watching instance of android.widget.TextView (android.widget.TextView received View#onDetachedFromWindow() callback) with key 4f991664-dc09-49b6-bcf2-a1fd02f512ef
* 
com.hjq.toast.demo I/.hjq.toast.dem: Explicit concurrent copying GC freed 12845(669KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 3956KB/7912KB, paused 643us total 67.394ms

* 是否必现【必填】：填是/否
* 每次必现

* 出现问题的手机信息【必填】：小米10s
* 出现问题的安卓版本【必填】：12

## 请回答

* 是部分机型还是所有机型都会出现【必答】：部分/全部（例如：某为，某 Android 版本会出现）
* 小米系列手机全部出现

* 框架最新的版本是否存在这个问题【必答】：是/否（如果用的是旧版本的话，建议升级看问题是否还存在）

* 是否已经查阅框架文档还未能解决的【必答】：是/否（文档会提供最常见的问题解答，可以看看是否有自己想要的）
是
* issue 是否有人曾提过类似的问题【必答】：是/否（看看曾经有人提过类似的问题，先参考一下别人是怎么解决的）
否
* 是否可以通过 Demo 来复现该问题【必答】：是/否（排查一下是不是自己的项目代码写得有问题导致的）
可以，您的demo可以复现，您多点几次
* 使用原生的 Toast 是否也会出现该问题【必答】：是/否（排查一下是不是框架的代码存在问题导致的）
没试过，吐司的地方太多了。
## 其他

本次出错比较明显，您亲测就可以看见
* 提供报错堆栈（如果有报错的话必填，注意不要拿被混淆过的代码堆栈上来）

* 提供截图或视频（根据需要提供，此项不强制）

* 提供解决方案（如果已经解决了的话，此项不强制）

**Comment by zkzk7749** [comment]
![625742fbb792d7ce9bbcb4e4f102b88](https://user-images.githubusercontent.com/18433246/180753587-9df0ad5a-8349-443a-9e9b-b98b090ec17c.jpg)

**Comment by getActivity** [comment]
<img width="647" alt="image" src="https://user-images.githubusercontent.com/28616817/181011090-eb3ed781-7b64-4f9d-a0a4-0ec85881809b.png">

<img width="579" alt="image" src="https://user-images.githubusercontent.com/28616817/181011134-2e9fdf54-9ca9-44e2-a694-785e7dcc3f2b.png">

**Comment by zkzk7749** [comment]
好的，感谢轮子哥
