### ISSUE TITLE
harmonyOS无法正常后台显示Toast(悬浮权限关闭的情况下) 

### ISSUE THREAD

**Issue by fys85** [getActivity/ToastUtils#98]
## 问题描述

* 框架版本【必填】：10.5

* 问题描述【必填】：harmonyOS无法正常后台显示Toast(悬浮权限关闭的情况下) 

* 复现步骤【必填】：ToastUtils的Demo，后台状态下显示Toast

* 是否必现【必填】：是

* 出现问题的手机信息【必填】：华为P40 harmonyOS2.0

* 出现问题的安卓版本【必填】：无

## 请回答

* 是部分机型还是所有机型都会出现【必答】：已知华为P40

* 框架最新的版本是否存在这个问题【必答】：是

* 是否已经查阅框架文档还未能解决的【必答】：是

* issue 是否有人曾提过类似的问题【必答】：否

* 是否可以通过 Demo 来复现该问题【必答】：是

* 使用原生的 Toast 是否也会出现该问题【必答】：是）

**Comment by fys85** [comment]
后台弹窗设置

**Comment by andasl** [comment]
这个是解决了吗？怎么解决的？我用这个库，在小米10上可以在屏幕正中心弹出toast，而不是下发水平中心弹出。在鸿蒙3上无法弹出

**Comment by andasl** [comment]
“请保证应用的通知栏权限或者悬浮窗权限处于开启的状态。”。只能手动设置后台弹窗吗
