### ISSUE TITLE
自定义图标是否可以考虑传入View对象

### ISSUE THREAD

**Issue by Jakewei** [getActivity/ToastUtils#99]
#### 问题描述

* ToastUtils.setView(int id); 例如我想自定义Toast的图标，那么是否每种图标都需对应一个布局文件，是否可以考虑传入View对象呢

#### 请回答

* issue 是否有人曾提过类似的问题？否

* 框架文档是否有提及到此问题？否

**Comment by getActivity** [comment]
小伙子，框架之所以不能直接传入 View，是因为每次显示 Toast 的时候都会去创建一个新的 Toast 对象和 View 对象，如果你传入的是一个 View 对象，那么怎么让框架在每次调用显示的时候创建呢？

**Comment by getActivity** [comment]
超过三天没有响应，自动关闭此 issue。
